# This is a basic workflow to help you get started with Actions

name: Sinbeard Blog CI/CD

# Controls when the action will run. 
on:
  # Triggers the workflow on push for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: 'us-east-1'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
        bundler-cache: true
    - name: "Bundle Install"
      working-directory: ./blog
      run: bundle install
    - name: "Build Site"
      working-directory: ./blog
      run: bundle exec jekyll build
      env:
        JEKYLL_ENV: production
    - name: "Deploy to AWS S3"
      run: aws s3 sync --size-only ./blog/_site/ s3://${{ secrets.AWS_S3_BUCKET_NAME }}
    - name: "Invalidate Cloudfront Cache to update site"
      run: aws cloudfront create-invalidation --distribution-id {{ secrets.AWS_CLOUDFRONT_DIST }} --paths "/*"
